#!/bin/bash
mysql  -uroot -p11111111 -e "CREATE USER IF NOT EXISTS '$MYSQL_USER_LOGIN'@'$MYSQL_ACCESS_IP' IDENTIFIED BY '$MYSQL_USER_PASSWORD';GRANT ALL ON *.* TO '$MYSQL_USER_LOGIN'@'$MYSQL_ACCESS_IP';"
mysql  -uroot -p11111111 -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;CREATE DATABASE IF NOT EXISTS rusacis;CREATE DATABASE IF NOT EXISTS lucera;CREATE DATABASE IF NOT EXISTS pwsoft; "

echo "mysql: Running Create $MYSQL_USER_LOGIN  User And 4 Databases"
