<?php
  
return [

    'list_class_id' => [
        0 => 'Human Fighter',
        1 => 'Human Warrior',
        2 => 'Human Gladiator',
        88 => 'Human Duelist',
        3 => 'Human Warlord',
        89 => 'Human Dreadnought',
        4 => 'Human Knight',
        5 => 'Human Paladin',
        90 => 'Human Phoenix Knight',
        6 => 'Human Dark Avenger',
        91 => 'Human Hell Knight',
        7 => 'Human Rogue',
        8 => 'Human Treasure Hunter',
        93 => 'Human Adventurer',
        9 => 'Human Hawkeye',
        92 => 'Human Sagittarius ',
        10 => 'Human Mage',
        11 => 'Human Wizard',
        12 => 'Human Sorceror',
        94 => 'Human Archmage',
        13 => 'Human Necromancer',
        95 => 'Human Soultaker',
        14 => 'Human Warlock',
        96 => 'Human Arcana Lord',
        15 => 'Human Cleric',
        16 => 'Human Bishop',
        97 => 'Human Cardinal',
        17 => 'Human Prophet',
        98 => 'Human Hierophant',
        15 => 'Human Cleric',
    

   
        18 => 'Elf Fighter',
        19 => 'Elf Knight',
        20 => 'Elf Temple Knight',
        99 => 'Elf EvaTemplar',
        21 => 'Elf Sword Singer',
        100 => 'Elf Sword Muse',
        22 => 'Elf Scout',
        23 => 'Elf Plains Walker',
        101 => 'Elf Wind Rider',
        24 => 'Elf Silver Ranger',
        102 => 'Elf Moonlight Sentinel',
        25 => 'Elf Mage',
        26 => 'Elf Wizard',
        27 => 'Elf Spell Singer',
        103 => 'Elf Mystic Muse',
        28 => 'Elf Elemental Summoner',
        104 => 'Elf Elemental Master',
        29 => 'Elf Oracle',
        30 => 'Elf Elder ',
        105 => 'Elf Eva Saint',
        31 => 'Dark Elf Fighter',
        32 => 'Dark Elf Paulus Knight',
        33 => 'Dark Elf Shillien Knight',
        106 => 'Dark Elf Shillien Templar',
        34 => 'Dark Elf Blade Dancer',
        107 => 'Dark Elf Spectral Dancer',
        35 => 'Dark Elf Assassin',
        36 => 'Dark Elf Abyss Walker',
        108 => 'Dark Elf Ghost Hunter',
        37 => 'Dark Elf Phantom Ranger',
        109 => 'Dark Elf Ghost Sentinel',
        38 => 'Dark Elf Mage',
        39 => 'Dark Elf Dark Wizard',
        40 => 'Dark Elf Spellhowler',
        110 => 'Dark Elf Storm Screamer',
        41 => 'Dark Elf Phantom Summoner',
        111 => 'Dark Elf Spectral Master',
        42 => 'Dark Elf Shillien Oracle',
        43 => 'Dark Elf Shillien Elder',
        112 => 'Dark Elf Shillien Saint',
        37 => 'Dark Elf Phantom Ranger',
        37 => 'Dark Elf Phantom Ranger',

    

   
        44 => 'Orc Fighter',
        45 => 'Orc Raider',
        46 => 'Orc Destroyer',
        113 => 'Orc Titan',
        47 => 'Orc Monk',
        48 => 'Orc Tyrant',
        114 => 'Orc Grand Khauatari',
        49 => 'Orc Mage',
        50 => 'Orc Shaman',
        51 => 'Orc Overlord',
        115 => 'Orc Dominator',
        52 => 'Orc Warcryer',
        116 => 'Orc Doomcryer',

    
   
        53 => 'Dwarf Fighter',
        54 => 'Dwarf Scavenger',
        55 => 'Dwarf Bounty Hunter',
        117 => 'Dwarf Fortune Seeker',
        56 => 'Dwarf Artisan',
        57 => 'Dwarf Warsmith',
        118 => 'Dwarf Maestro',
        49 => 'Orc Mage',
        50 => 'Orc Shaman',
        51 => 'Orc Overlord',
        115 => 'Orc Dominator',
        52 => 'Orc Warcryer',
        116 => 'Orc Doomcryer',
    ]
    
];